apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: traq-dev-backend
  name: traq-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: traq-dev-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: traq-dev-backend
    spec:
      nodeSelector:
        kubernetes.io/hostname: s512.tokyotech.org
      containers:
        - image: ghcr.io/traptitech/traq:master@sha256:2e7c3b54902cc1e30ed12b3e6b58b8001c88f431fad4b07cb12b962817ec932c
          args: ["serve", "--pprof"]
          name: traq-dev-backend
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /keys
              name: keys
              readOnly: true
            - mountPath: /app/config.yml
              name: config-yml
              readOnly: true
              subPath: config.yml
      restartPolicy: Always
      volumes:
        - name: config-yml
          secret:
            secretName: traq-dev-backend-config-yml
        - name: keys
          secret:
            secretName: traq-dev-backend-secrets
