apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: traq-dev-frontend
  name: traq-dev-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traq-dev-frontend
  template:
    metadata:
      labels:
        app: traq-dev-frontend
    spec:
      nodeSelector:
        kubernetes.io/hostname: s512.tokyotech.org
      containers:
        - image: ghcr.io/traptitech/traq-ui:master@sha256:47b5544deec5930ec57953efc78a86d6f1e0bf2adefb3c25aa3eb26c0de62cb5
          name: traq-dev-frontend
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
