apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: traq-dev-frontend
  name: traq-dev-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traq-dev-frontend
  template:
    metadata:
      labels:
        app: traq-dev-frontend
    spec:
      nodeSelector:
        kubernetes.io/hostname: s512.tokyotech.org
      containers:
        - image: ghcr.io/traptitech/traq-ui:master@sha256:0074d279670b136a7ad7d33c82b8350c2f3901668948a6803bfd24cafc6e9031
          name: traq-dev-frontend
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
