apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: traq-dev-frontend
  name: traq-dev-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: traq-dev-frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: traq-dev-frontend
    spec:
      nodeSelector:
        kubernetes.io/hostname: c1-203.tokyotech.org
      containers:
        - image: ghcr.io/traptitech/traq-ui:master@sha256:e61c678ec35f94ecc7a6282d149d830bc59c355104512363a18825ce600bdec7
          name: traq-dev-frontend
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
