apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: traq-dev-frontend
  name: traq-dev-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: traq-dev-frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: traq-dev-frontend
    spec:
      nodeSelector:
        kubernetes.io/hostname: c1-203.tokyotech.org
      containers:
        - image: ghcr.io/traptitech/traq-ui:master@sha256:5a7a2aaf4159480e9d0b459476b7c266bf464dd7c6d8fac4919596e9fe1f7918
          name: traq-dev-frontend
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
