apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: booq-certificate

spec:
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer
  secretName: booq-tls                #適当に決めたがこれでいいかわからない
  duration: 2160h0m0s # 90d
  renewBefore: 720h0m0s # 30d
  dnsNames:
    - booq.trap.jp                    #わからない
