apiVersion: v1
kind: Deployment
metadata:
  name: booq
  labels:
    app: booq

spec:
  selector:
    matchLabels:
      app: booq
  template:
    metadata:
      labels:
        app: booq
    spec:
      nodeSelector:
        kubernetes.io/arch: booq                    #ここわからない

      containers:

        - name: booq-frontend
          image: ghcr.io/traptitech/booq-ui:latest
          env:
            - name: booq_port-client
              valueFrom:
                secretKeyRef:
                  name: booq-secrets
                  key: booq_port-client
          # resources:
          #   requests:
          #     memory: "128Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "256Mi"
          #     cpu: "500m"

        - name: booq-backend
          image: ghcr.io/traptitech/booq:latest
          env:
            - name: booq_port-server
              valueFrom:
                secretKeyRef:
                  name: booq-secrets
                  key: booq_port-server
          envFrom:
            - secretRef:
                name: booq-secrets
          # resources:
          #   requests:
          #     memory: "128Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "256Mi"
          #     cpu: "500m"