apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: booq-ingressroute

spec:
  entryPoints:
    - websecure
  tls:
    secretName: booq-tls
  routes:
    - kind: Rule
      match: Host(`booq.trap.jp`)
      middlewares:
        - name: auth-trap-jp-hard
          namespace: auth
      services:
        - kind: Service
          name: booq-frontend
          port: 80
          scheme: http
        - kind: Service
          name: booq-backend
          port: 3001
          scheme: http