apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-dashboard-staging
  labels:
    sablier.enable: "true"
    sablier.group: preview-ns-staging

spec:
  # replicas: 1 # Autoscale by sablier
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ns-dashboard-staging
  template:
    metadata:
      labels:
        app: ns-dashboard-staging
    spec:
      enableServiceLinks: false

      containers:
        - name: ns-dashboard
          image: ghcr.io/traptitech/ns-dashboard:main@sha256:fa85af6897c12770e25608a6a260c527bb7fb67c27d3c344c0589150ed9bafa9
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
