apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-dashboard-staging
  labels:
    sablier.enable: "true"
    sablier.group: preview-ns-staging

spec:
  # replicas: 1 # Autoscale by sablier
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ns-dashboard-staging
  template:
    metadata:
      labels:
        app: ns-dashboard-staging
    spec:
      enableServiceLinks: false

      containers:
        - name: ns-dashboard
          image: ghcr.io/traptitech/ns-dashboard:main@sha256:1d205405daab7dbe26eeb215ad45145af0f62a29db99cab236b313437acf8e8d
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
