apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-dashboard-staging
  labels:
    sablier.enable: "true"
    sablier.group: preview-ns-staging

spec:
  # replicas: 1 # Autoscale by sablier
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ns-dashboard-staging
  template:
    metadata:
      labels:
        app: ns-dashboard-staging
    spec:
      enableServiceLinks: false

      containers:
        - name: ns-dashboard
          image: ghcr.io/traptitech/ns-dashboard:main@sha256:cedeb17cbbdcc3c6e2aaaae8c3ed271a7f1c10d3c9d3b148fdf5b77663efe8e5
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
